server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: user
        uri: lb://user/
        predicates:
          - Path=/user/**
      - id: event
        uri: lb://event/
        predicates:
          - Path=/event/**
      - id: search
        uri: lb://search/
        predicates:
          - Path=/search/**
      - id: ticket
        uri: lb://ticket/
        predicates:
          - Path=/ticket/**
