server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: user
        uri: lb://user/
        predicates:
          - Path=/user/**
      - id: user
        uri: lb://user/
        predicates:
          - Path=/event/**
